baseURL = 'https://ashleyzhiyin.github.io/'
languageCode = 'en-us'
title = 'Zhiyin Zhang Home Page'
theme = 'hugo-theme-nix'

[params]
  Name           = "Zhiyin Zhang"
  HeaderUsername = "ashleyzhiyin"
  HeaderHostname = "github.io"
  About          =  """
Hi, Iâ€™m Zhiyin (Ashley) Zhang. I am a future asset analyst with quantitative insights to support investment decisions.

# Career Focus
- Asset / risk management
- Currently exploring opportunities in Hong Kong / Singapore / US buy-side firms

# Experience
- Equity Analyst Intern: WorldQuant Brain (Singapore)
- Equity Analyst Intern: China International Capital Corporation Limited (Shanghai, China)
- Investment Member: Wharton PE/VC Club ï½œ Wharton Chinese Association (Philadelphia, US)

# Education
- Social Policy in Economic Track (M.S.) | University of Pennsylvania
- Computer Science (M.S.) | Northern Arizona University
- Applied Linguistics (B.A.) | Wuhan University

# Skills
- Investment research & asset allocation (Equity / Multi-asset / ETFs / Alternatives)
- Quantitative modeling: time-series analysis, risk modelling (VaR / GARCH), forecasting
- Corporate valuation & financial modeling (DCF, comparable analysis, capital budgeting)
- Data-driven decision-making in finance (econometrics, optimization, simulation)

# ğŸ”— Letâ€™s Connect
- ğŸ“§ Email: zhiyinzh@upenn.edu
- ğŸ’¼ LinkedIn: Zhiyin-Zhang (linkedin.com/in/zhiyin-zhang-3402412b9)
- ğŸ“ Location: Philadelphia Â· Singapore/HK, willing to relocate
"""

  ProfilePicture = "images/avatar.jpg"
  GithubID       = "ashleyzhiyin"
  LinkedinID     = "zhiyin-zhang-3402412b9/"
  Email          = "zhiyinzh@upenn.edu"
  


[menu]
  [[menu.header]]
    identifier = "post"
    name       = "posts"
    weight     = 0

  [[menu.header]]
    parent = "post"
    name   = "All Posts"
    url    = "/posts"

  [[menu.header]]
    name   = "About"
    url    = "/about"
    weight = 10
