baseurl = "https://ashleyzhiyin.github.io"
title = "Zhiyin Zhang's Homepage"
theme = "hugo-theme-cleanwhite"
languageCode = "en-us"
preserveTaxonomyNames = true
hasCJKLanguage = true

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "Algolia"]

[params]
  header_image = "images/sfo4.jpg"
  SEOTitle = "张芷茵的主页 | Zhiyin Zhang's Homepage"
  description = "Zhiyin(Ashley) Zhang ｜ finance analyst "
  keyword = "张芷茵, Zhiyin Zhang, Ashley, 博客, 个人网站, 互联网, Finance, 金融"
  slogan = "Only by ignoring the noise can you see who you truly are."
  upstreamAttribution = false

  image_404 = "img/404-bg.jpg"
  title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # Sidebar settings
  sidebar_about_description = "Hi, I’m Zhiyin(Ashley) Zhang. I am a future asset analyst with quantitative insights to support investment decisions."
  sidebar_avatar = "images/avatar.jpg"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = false 
  featured_condition_size = 1 

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  [params.social]
  rss            = false 
  email          = "zhiyinzh@upenn.edu"
  linkedin       = "https://www.linkedin.com/in/zhiyin-zhang-3402412b9"
  github         = "https://github.com/ashleyzhiyin"
  
  [[params.friend_link]]
  title = "Haifei's Homepage"
  href =  "https://hfwang132.github.io"
  [[params.additional_menus]]
  title =  "ABOUT"
  href =  "/about/"

[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 2
    startLevel = 1
  [markup.highlight]
    style = "dracula"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
