baseURL = 'https://ashleyzhiyin.github.io/'
languageCode = 'en-us'
title = 'Zhiyin Zhang Home Page'
theme = 'hugo-theme-nix'

[params]
  Name           = "Zhiyin Zhang"
  HeaderUsername = "ashleyzhiyin"
  HeaderHostname = "github.io"
  About          = "Hi, Iâ€™m Zhiyin(Ashley) Zhang. I am a future asset analyst with quantitative insights to support investment decisions."
  ProfilePicture = "images/avatar.jpg"
  GithubID       = "ashleyzhiyin"
  LinkedinID     = "zhiyin-zhang-3402412b9/"
  Email          = "zhiyinzh@upenn.edu"
  

[menu]
  [[menu.header]]
    identifier = "post"
    name       = "posts"
    weight     = 0

  [[menu.header]]
    parent = "post"
    name   = "All Posts"
    url    = "/posts"

  [[menu.header]]
    name   = "About"
    url    = "/about"
    weight = 10
