baseURL = 'https://ashleyzhiyin.github.io/'
languageCode = 'en-us'
title = 'Zhiyin Zhang Home Page'
theme = 'hugo-theme-nix'

[params]
  Name           = "Zhiyin Zhang"
  HeaderUsername = "ashleyzhiyin"
  HeaderHostname = "github.io"
  About          = "Hi, I‚Äôm Zhiyin(Ashley) Zhang. I am a future asset analyst with quantitative insights to support investment decisions."
  ProfilePicture = "images/avatar.jpg"
  GithubID       = "ashleyzhiyin"
  LinkedinID     = "zhiyin-zhang-3402412b9/"
  Email          = "zhiyinzh@upenn.edu"
  
# Career Focus
- Asset/risk management 
- Currently exploring opportunities in Hong Kong / Singapore / US buy-side firms


# Experience
- Equity Analyst Intern: World Quant Brain (Singapore)
- Equity Analyst Intern: China International Capital Corporation Limited (China Shanghai)
- Investment Member: Wharton PE/VC Club ÔΩú Wharton Chinese Association (US PA) 

# Education
- Social Policy in Economic Track (M.S) | University ofPennsylvania  
- Computer Science (M.S) | Northern Arizona University
- Applied Linguistic (B.A) | Wuhan University


# Skills
- Investment research & asset allocation (Equity / Multi-asset / ETFs / Alternatives)
- Quantitative modeling: time-series analysis, risk modelling (VaR / GARCH), forecasting
- Corporate valuation & financial modeling (DCF, comparable analysis, capital budgeting)
- Data-driven decision-making in finance (econometrics, optimization, simulation)


# üîó Let‚Äôs Connect
- üìß Email: zhiyinzh@upenn.edu
- üíº LinkedIn: [Zhiyin-Zhang](https://www.linkedin.com/in/zhiyin-zhang-3402412b9)
- üìç Location: Philadelphia ¬∑ Singapore/HK willing to relocate


[menu]
  [[menu.header]]
    identifier = "post"
    name       = "posts"
    weight     = 0

  [[menu.header]]
    parent = "post"
    name   = "All Posts"
    url    = "/posts"

  [[menu.header]]
    name   = "About"
    url    = "/about"
    weight = 10
